[build]
  command = "npm install"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg", "pg-native"]
  included_files = ["db/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200